YS = ["y_qn", "y_05", "y_1", "y_25", "y_5", "y_10", "y_NN"]
RES = ["DEGenes", "DEGenes_05", "DEGenes_1", "DEGenes_25", "DEGenes_5", "DEGenes_10", "DEGenes_NN"]
TABS = ["FriedmanOriginalQnUp", "FriedmanQnDp05Up", "FriedmanQnDp1Up", "FriedmanQnDp25Up", "FriedmanQnDp5Up", "FriedmanQnDp10Up", "FriedmanOriginalNNUp", "FriedmanOriginalQnDown", "FriedmanQnDp05Down", "FriedmanQnDp1Down", "FriedmanQnDp25Down", "FriedmanQnDp5Down", "FriedmanQnDp10Down", "FriedmanOriginalNNDown"]

rule all:
    input:
        expand( "/tmp/repo/DGE_LADC/results/{tabs}.csv", tabs = TABS)

rule preprocessing_expressionMatrix:
    input:
        "/tmp/repo/DGE_LADC/data/cancerData"
    output:
        "/tmp/repo/DGE_LADC/results/expression_matrix.RData"
    conda:
        "/tmp/repo/DGE_LADC/workflow/envs/Renv.yaml"
    script:
        "/tmp/repo/DGE_LADC/workflow/scripts/expressionMatrix.R"

rule preprocessing:
    input:
        "/tmp/repo/DGE_LADC/results/expression_matrix.RData",
        "/tmp/repo/DGE_LADC/data/Metadata/gdc_sample_sheet.2021-04-15.tsv",
        "/tmp/repo/DGE_LADC/data/Metadata/41467_2013_BFncomms3612_MOESM488_ESM_genes.csv"
    output:
        "/tmp/repo/DGE_LADC/results/y_coding.RData",
        "/tmp/repo/DGE_LADC/results/y_tme.RData"
    conda:
        "/tmp/repo/DGE_LADC/workflow/envs/Renv.yaml"
    script:
        "/tmp/repo/DGE_LADC/workflow/scripts/preprocessing.R"

rule normalisation:
    input:
        "/tmp/repo/DGE_LADC/results/y_tme.RData",
    output:
        expand("/tmp/repo/DGE_LADC/results/{ys}.RData", ys=YS)
    conda:
        "/tmp/repo/DGE_LADC/workflow/envs/Renv.yaml"
    script:
        "/tmp/repo/DGE_LADC/workflow/scripts/normalisation.R"

rule DGEa:
    input:
        expand(["/tmp/repo/DGE_LADC/results/{ys}.RData","/tmp/repo/DGE_LADC/data/Metadata/The_differentially_expressed.csv"], ys=YS)
    output:
        expand("/tmp/repo/DGE_LADC/results/{res}.csv", res = RES)
    conda:
        "/tmp/repo/DGE_LADC/workflow/envs/Renv.yaml"
    script:
        "/tmp/repo/DGE_LADC/workflow/scripts/dge.R"

rule analysis:
    input:
        expand(["/tmp/repo/DGE_LADC/data/Metadata/The_differentially_expressed.csv", "/tmp/repo/DGE_LADC/results/{res}.csv"], res = RES)
    output:
        expand("/tmp/repo/DGE_LADC/results/{tabs}.csv", tabs = TABS)
    conda:
        "/tmp/repo/DGE_LADC/workflow/envs/Renv.yaml"
    script:
        "/tmp/repo/DGE_LADC/workflow/scripts/results_analysis.R"
